<script type="text/javascript" src="resources/scripts/specific/liste.js"></script>

<form method="get" action="index.php" class="form">
    <input type="hidden" name="website" value="<?php echo $website ?>" />
    <input type="hidden" name="device" value="<?php echo $device ?>" />
    <input type="hidden" name="query" value="<?php echo $query ?>" /> <input
        type="hidden" name="date[from]"
        value="<?php echo $interval['base']['from'] ?>" /> <input
        type="hidden" name="date[to]"
        value="<?php echo $interval['base']['to'] ?>" /><input
        type="text" id="search" name="search"
        value="<?php echo $search ?>" list="filters"></input>
    <button type="submit" class="google">Filter</button>
    <div class="help-tip">
        <p>
            <strong>Search Filter</strong><br /> <br />
            Spaces ( ) are counted as an OR operator.<br/><br/>
            When you use a dash (-) before a word, it excludes all items with that info from your results.<br />
            Example: <i>jaguar speed -car</i><br />
            <br />When you put a word or sentence in simple quotes ('), the results will only include results with the same words
            in the same order as the ones inside the quotes.<br/>
            Only use this if you're looking for an exact word or phrase, otherwise you'll exclude many helpful results by mistake.
            <br />Example: <i>'imagine all the people'</i> or <i>'aston martin'</i><br /> <br />
            Add an asterisk (*) as a placeholder for any unknown or wildcard terms.
            <br />Example: <i>'/homes/*/rentals/'</i>
            <br /> <br />
            To search all items that must begin by a specific term, use (^).
            <br />Similarly to specifiy search with a term that must end each item, use ($). <br />Example : <i>'^/$'</i>
        </p>
    </div>

    <!-- <button id="filter-handling" class="google right">Configuration</button> -->
    <a class="margin-left"
        href="index.php?website=<?php echo $website ?>&device=<?php echo $device ?>&query=<?php echo $query ?><?php echo (isset($interval['base']) ? '&date[from]=' . $interval['base']['from'] . '&date[to]=' . $interval['base']['to'] : '') ?><?php echo (isset($search) ? '&search=' . $search : '') ?>&compare">
        <button type="button" class="google">Compare with previous Period</button>
    </a> <a class="no-margin"
        href="index.php?website=<?php echo $website ?>&device=<?php echo $device ?>&query=<?php echo $query ?><?php echo (isset($interval['base']) ? '&date[from]=' . $interval['base']['from'] . '&date[to]=' . $interval['base']['to'] : '') ?><?php echo (isset($search) ? '&search=' . $search : '') ?>&compare=year">
        <button type="button" class="google">Or previous Year</button>
    </a>
    <div class="help-tip">
        <p>
            <strong>Compare with the previous period</strong><br />
            <br />Comparison is always done with the previous period to date.<br />
            Example : Day <i>D</i> will always be compared to <i>D - 1</i> <br />Period from <i>D to
                D - 28</i> will be compared to <i>D - 29 to D - 56</i>
        </p>
    </div>

     <a class="margin-left"
        href="index.php?website=<?php echo $website ?>&mode=detail&device=<?php echo $device ?>&query=<?php echo $query ?>&search=<?php echo $search ?>&aggregate"><button
            type="button" class="google">
            <span>See <?php echo ($query == 'query') ? 'keywords' : 'pages' ?> evolution in time for current filter</span>
        </button></a>
    <div class="help-tip">
        <p>
            <strong>Visualization of <?php echo ($query == 'query') ? 'keywords' : 'pages' ?> evolution in time for current filter</strong><br />
            <br />Display sums of impressions, clicks and CTR, day by day for <?php echo ($query == 'query') ? 'keywords' : 'pages' ?> matching current filter <i>'<?php echo (strlen($search) > 16) ? substr($search, 0, 15) . '...' : $search ?>'</i>
        </p>
    </div>
</form>

<datalist id="filters">
<?php
foreach ($filters as $filter) {
    ?>
  <option label="<?php echo $filter[0] ?>"
        value="<?php echo $filter[2] ?>">
<?php
}
?>
</datalist>

<?php echo count($data)?> Results<?php echo (($compare !== false) ? ', compared with previous period' : '')?>

<table id="list" class="tablesorter">
    <thead>
        <tr>
            <th></th>
            <th class="query left"><?php echo ucfirst($query) ?></th>
            <th class="impressions">Impressions</th>
            <?php if ($compare !== false) { ?><th class="compare">%</th><?php } ?>
            <th class="clicks">Clicks</th>
            <?php if ($compare !== false) { ?><th class="compare">%</th><?php } ?>
            <th class="ctr">CTR</th>
            <?php if ($compare !== false) { ?><th class="compare"></th><?php } ?>
            <th class="position">Position</th>
            <?php if ($compare !== false) { ?><th class="compare"></th><?php } ?>
        </tr>
    </thead>
    <tbody>
<?php
$count = 1;

foreach ($data as $item) {
    ?>
<tr
            data-href="index.php?website=<?php echo $website ?>&device=<?php echo $device ?>&query=<?php echo $query ?>&mode=detail&search=<?php echo urlencode($item[0]) ?>"
            class="clickable<?php if ($count % 2) { echo ' odd'; $odd = false; } else { $odd = true; } ?>">
            <td class="left"><?php echo $count++; ?></td>
            <td class="left"><?php echo $item[0]; ?></td>
            <td><?php echo $item[1] ?></td>
            <?php
    if ($compare !== false) {
        $percentage = isset($compare['#' . $item[0]]) && ($compare['#' . $item[0]][1] > 0) ? round(($item[1] - $compare['#' . $item[0]][1]) / $compare['#' . $item[0]][1] * 100) : null;
        ?><td class="_i"><?php echo (($percentage > 0) ? '+' : '') . (($percentage > 999) ? '&infin;' : $percentage) ?></td><?php } ?>
            <td><?php echo $item[2] ?></td>
            <?php
    if ($compare !== false) {
        $percentage = isset($compare['#' . $item[0]]) && ($compare['#' . $item[0]][2] > 0) ? round(($item[2] - $compare['#' . $item[0]][2]) / $compare['#' . $item[0]][2] * 100) : null;
        ?><td class="_i"><?php echo (($percentage > 0) ? '+' : '') . (($percentage > 999) ? '&infin;' : $percentage) ?></td><?php } ?>
            <td><?php echo round($item[2] / $item[1] * 100, 0) ?> %</td>
            <?php

    if ($compare !== false) {
        $difference = isset($compare['#' . $item[0]]) && ($compare['#' . $item[0]][1] > 0) ? round($item[2] / $item[1] * 100, 0) - round($compare['#' . $item[0]][2] / $compare['#' . $item[0]][1] * 100, 0) : null;
        ?><td class="_c"><?php echo (($difference > 0) ? '+' : '') . $difference ?></td><?php } ?>
            <td><?php echo $item[3] ?></td>
            <?php
    if ($compare !== false) {
        $difference = isset($compare['#' . $item[0]]) ? $item[3] - $compare['#' . $item[0]][3] : null;
        ?><td class="_p"><?php echo (($difference > 0) ? '+' : '') . $difference ?></td><?php } ?>
            </tr>
<?php
    # Performance Fix
    if ($count > 5000) {
        break;
    }
}
?>
</tbody>
</table>

<div id="filter-overlay"></div>
<div id="filter-popup">
    Gestion des Filtres
    <div>
        <span>Filtre *</span> <input type="text" id="filter-value"
            name="value" value="<?php echo $search ?>" list="filters" />
    </div>
    <div>
        <span>Nom *</span> <input type="text" id="filter-name" value="" />
    </div>
    <div class="center">
        <button id="filter-delete" class="google">Supprimer</button>
        <button id="filter-add" class="google">Ajouter / Modifier</button>
        <div class="help-tip">
            <p>
                <strong>Filtre de Recherche</strong><br /> <br /> Le
                champ <i>Filtre</i> contient toujours le filtre en cours
                d'utilisation sur le site, chaque Filtre est identifié
                par son nom, qui est unique<br /> <br /> <strong>Ajouter
                    un filtre</strong> <br />Pour enregistrer un nouveau
                filtre, spécifiez le nom de ce filtre, puis cliquez sur
                <i>Ajouter</i><br /> <br /> <strong>Modification/Suppression
                    de filtre</strong><br /> Selectionnez le filtre,
                procedez aux changements puis cliquez sur <i>Modifier</i>
                ou <i>Supprimer</i> <br /> <br /> Il n'y a aucun message
                de validation/erreur.

        </div>
        </p>
    </div>
</div>

<?php
$preservals = array();
$removals = array();

# Finding Negatives
preg_match_all('/^(?:\-\'([^\']+)\'|\-([^\' ]+))/i', $search, $removal, PREG_SET_ORDER);
foreach ($removal as $remove) {
    if (empty(trim(end($remove))) === false) {
        $removals[] = strtolower(current($remove));
    }
    $search = str_replace(reset($remove), '', $search);
}

preg_match_all('/(?:\-\'([^\']+)\'|[^\w]\-([^\' ]+))/i', $search, $removal, PREG_SET_ORDER);
foreach ($removal as $remove) {
    if (empty(trim(end($remove))) === false) {
        $removals[] = strtolower(current($remove));
    }
    $search = str_replace(reset($remove), '', $search);
}

# Adding Positives Search
preg_match_all('/(?:\'([^\']+)\'|([^\' ]+))/i', $search, $preserval, PREG_SET_ORDER);
foreach ($preserval as $preserve) {
    if (empty(trim(end($preserve))) === false) {
        $preservals[] = strtolower(current($preserve));
    }
}
?>
<div class="status">
    <span class="left">
<?php echo ($query == 'query') ? ' Keywords' : ' Pages' ?> <?php
if (count($preservals) > 0) {
    ?>
containing <i>'<?php echo implode('\'</i> or <i>\'', $preservals) ?>'</i>
<?php
}
if (count($removals) > 0) {
    ?>
<?php echo (count($preservals) > 0) ? ' and ' : ''?>
not containing <i>'<?php echo implode('\'</i> neither <i>\'', $removals) ?>'</i>
<?php
}
?>
<?php echo html_interval($interval); ?>
</span> <span class="right blue">Click on a line to obtain <?php echo ($query == 'query') ? ' Keyword' : ' Page' ?> evolution in time</span>
</div>